/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CifradoCesar */

#ifndef _Included_CifradoCesar
#define _Included_CifradoCesar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CifradoCesar
 * Method:    cifrar
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CifradoCesar_cifrar
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     CifradoCesar
 * Method:    descifrar
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CifradoCesar_descifrar
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
